<?xml version="1.0" encoding="utf-8"?>
<schedule_info MachineName="ENSIS3015AJ">
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-97</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-98</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-99</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-01</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-02</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-03</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6684-04</parts_name>
    <product_quantity>2</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>4</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
</schedule_info>