<?xml version="1.0" encoding="utf-8"?>
<schedule_info MachineName="ENSIS3015AJ">
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-12</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-13</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-14</parts_name>
    <product_quantity>2</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-15</parts_name>
    <product_quantity>2</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-16</parts_name>
    <product_quantity>4</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-17</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
  <parts_info>
    <server_name />
    <folder_name />
    <parts_name>6670-18</parts_name>
    <product_quantity>1</product_quantity>
    <reception_quantity>0</reception_quantity>
    <rejection_quantity>0</rejection_quantity>
    <complete_code>2</complete_code>
    <thickness>5</thickness>
    <material_name>1.0037</material_name>
    <punch_number>0</punch_number>
    <die_number>0</die_number>
    <utilization>0</utilization>
  </parts_info>
</schedule_info>
